name            : imagebutton_example
description     : Demonstrates how to use the image_button plugin.
publish_to      : 'none'

environment     :
  sdk: '>=3.2.6 <4.0.0'

dependencies    :
  flutter        :
    sdk: flutter

  imagebutton    :
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test    :
    sdk: flutter
  flutter_lints   : ^2.0.0

flutter         :
  uses-material-design: true
  assets              :
    - assets/